version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./back/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_METRICS_ENABLED=true
      - GF_METRICS_ENDPOINT_ENABLED=true

  backend:
    build: ./back
    command: sh ./dev.sh
    volumes:
      - ./back:/app
    ports:
      - "3000:3000"
    networks:
      - monitoring
    env_file:
      - ./back/.env

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
